version: '2.4'
services:
  mail:
    image: "mailhog/mailhog"
    ports:
      - 1025:1025
      - 8025:8025
  mariadb:
    image: "mariadb:10.5.3"
    restart: always
    networks:
      - food-test
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: foodtest
      MYSQL_PASSWORD: foodtest
      MYSQL_USER: fooduser
      MYSQL_DATABASE: food_test
    ports:
      - 3306:3306
    volumes:
      - ./data/:/var/lib/mysql
networks:
  food-test:
    driver: bridge